### ISSUE TITLE
RTL support for ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by sosharma1403** [zefoy/ngx-perfect-scrollbar#180]

**Comment by sconix** [comment]
I am not too keen on adding rtl support in the wrapper, it really should be added to the perfect-scrollbar. For it there is already an issue to fix the RTL support.

**Comment by kyoz** [comment]
@sosharma1403 Since the perfect-scrollbar doesn't support it yet (There's an PR already since 2017, hope they'll merge it soon). And this is how i doing:

Add these in perfect-scrollbar css (after .ps__rail-y and .ps__thumb-y):

```css
*[dir=rtl] .ps__rail-y {
    right: unset !important;
    left: 0px !important;
}

*[dir=rtl] .ps__thumb-y {
    right: unset !important;
    left: 2px !important;
}
```

I do set dir attribute to the container div. so that's my css, you can adapt it to work properly for you.

P/s: don't forget to use to use `suppressScrollX` to prevent glitchy behavior.

Hope it help

**Comment by FloNeu** [comment]
As i didn't want to open a new question for that... how to you guys abbly perfect scrollbar to the table body? Pretty new to using this component - couldn't really find a way to do it... help would be much appreciate.

**Comment by MRebati** [comment]
there is just a quick work-around on this one:

```css
.ps{
    direction: ltr;
}

.ps-content{
    direction: rtl;
}
```

otherwise 5px of the content on the right doesn't show.
