### ISSUE TITLE
CSS bug: size inherit prevents using calc() on parent

### ISSUE THREAD

**Issue by PeterHewat** [zefoy/ngx-perfect-scrollbar#262]
The size of the main container is set to inherit as we can see here [perfect-scrollbar.component.css L.81](https://github.com/zefoy/ngx-perfect-scrollbar/blob/master/src/lib/perfect-scrollbar.component.css#L81):
```css
perfect-scrollbar > .ps {
  position: static;

  display: block;
  width: inherit;
  height: inherit;
  max-width: inherit;
  max-height: inherit;
}
```
The problem with this is that if the parent element has its size set using a calculation (ex: height: calc(100% - 64px)), the child also performs this calculation.
To fix this issue, all you have to do is set the width and height to 100% instead.
